### ISSUE TITLE
this does not work for build

### ISSUE THREAD

**Issue by CConchelos** [zLulus/NotePractice#135]
the sqlite dll for visualscripting is limited to editor only. I could not build a small project for standalone, if you cannot build this solution cannot be used for anything you wish to ship. I love the idea though, it's too bad sqlite3 is already integrated but they restrict access.

**Comment by zLulus** [comment]
Yes, using sqlite in Unity is causing me a lot of headaches as well, here's some of what I have documented: https://www.cnblogs.com/Lulus/p/16459845.html. I hope this helps.
